version = 3

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground = "#6c7086"
    template = "┌ "

  [[blocks.segments]]
    type = "session"
    style = "plain"
    foreground = "#cdd6f4"
    template = "{{ if .SSHSession }}\ueba9 {{ end }}"
    [blocks.segments.properties]
      display_host = true

  [[blocks.segments]]
    type = "os"
    style = "plain"
    foreground = "#ffffff"
    template = "{{ .Icon }} "

  [[blocks.segments]]
    type = "session"
    style = "plain"
    foreground = "#bac2de"
    template = "{{ .UserName }} on "

  [[blocks.segments]]
    type = "path"
    style = "plain"
    foreground = "#f5c2e7"
    template = " {{ .Path }} "
    [blocks.segments.properties]
      folder_separator_icon = "/"
      style = "full"

  [[blocks.segments]]
    type = "git"
    style = "plain"
    template = " {{ .HEAD }} "
    foreground = "#cba6f7"
    foreground_templates = [
      "{{ if and (not .Working.Changed) (not .Staging.Changed) (eq .Ahead 0) (eq .Behind 0) }}#a6e3a1{{ end }}",
      "{{ if or (.Working.Changed) (.Staging.Changed) }}#fab387{{ end }}",
      "{{ if or (gt .Ahead 0) (gt .Behind 0) }}#f38ba8{{ end }}"
    ]

[[blocks]]
  type = "prompt"
  alignment = "right"

  [[blocks.segments]]
    type = "python"
    style = "plain"
    foreground = "#f9e2af"
    template = " {{ .Venv }} {{ .Full }} "

  [[blocks.segments]]
    type = "node"
    style = "plain"
    foreground = "#a6e3a1"
    template = " {{ .Full }} "

  [[blocks.segments]]
    type = "container"
    style = "plain"
    foreground = "#89b4fa"
    template = " "

  [[blocks.segments]]
    type = "swift"
    style = "plain"
    foreground = "#f38ba8"
    template = "ﯣ {{ .Full }} "

  [[blocks.segments]]
    type = "executiontime"
    style = "plain"
    foreground = "#f5e0dc"
    template = "{{ .FormattedMs }} "
    [blocks.segments.properties]
      threshold = 0

  [[blocks.segments]]
    type = "time"
    style = "plain"
    foreground = "#cdd6f4"
    template = "{{ .CurrentDate | date \"15:04:05\" }}"

[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "text"
    style = "plain"
    foreground = "#6c7086"
    template = "└ "

  [[blocks.segments]]
    type = "status"
    style = "plain"
    template = "{{ if eq .Code 0 }}<#89b4fa>❯ </>{{ else }}<#f38ba8>❯ </>{{ end }}"
    [blocks.segments.properties]
      always_enabled = true

[transient_prompt]
background = "transparent"
foreground = "#ffffff"
template = "{{ if eq .Code 0 }}<#89b4fa>❯ </>{{ else }}<#f38ba8>❯ </>{{ end }}"
